### ISSUE TITLE
cannot be installed

### ISSUE THREAD

**Issue by biohubx** [jokergoo/InteractiveComplexHeatmap#50]
Hello,
    I try to install this nice heatmap package, but it can not be intsalled in R.
> BiocManager::install("InteractiveComplexHeatmap")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.2 (2020-06-22)
Installing package(s) 'InteractiveComplexHeatmap'
Warning message:
package ‘InteractiveComplexHeatmap’ is not available (for R version 4.0.2)

Do I need to upgrade the R?
Do you have any suggestions for this issue?
Best,

**Comment by jokergoo** [comment]
Now it is only in the development brach on Bioconductor.

Or you can directly install it from GitHub:

```r
library(devtools)
install_github("jokergoo/InteractiveComplexHeatmap")
```
