### ISSUE TITLE
Use with shiny modules

### ISSUE THREAD

**Issue by whtns** [jokergoo/InteractiveComplexHeatmap#51]
Is it possible to run an InteractiveComplexHeatmap through a shiny [module](https://mastering-shiny.org/scaling-modules.html)? I am surprised that the following doesn't seem to work
```

library(shiny)
library(InteractiveComplexHeatmap)



plotHeatmapui <- function(id){
    ns <- NS(id)
    tagList(
        htmlOutput(ns("heatmap_output"))
        )
    }

plotHeatmap <- function(input, output, session){
    ns <- session$ns
    m = matrix(rnorm(100), 10)
    ht = Heatmap(m)
    InteractiveComplexHeatmapWidget(input, output, session, ht, output_id = ns("heatmap_output"))
}


ui = fluidPage(
    # Copy in UI
    plotHeatmapui("plotHeatmapui")
)

server = function(input, output, session) {
    callModule(plotHeatmap, "plotHeatmapui")
}
shiny::shinyApp(ui, server)
```

**Comment by jokergoo** [comment]
I don't know. I haven't learnt shiny module yet :)

**Comment by jokergoo** [comment]
I have quickly checked the "master Shiny" book and it says :

> In the module UI, the namespacing is explicit: you have to call NS(id, "name") every time you create an input or output.

In InteractiveComplexHeatmap, there are so many `input` and `output`, also these IDs are used in CSS and Javascript code, so currently I think it is quite difficult or a lot of work to do to support shiny modules.

I put it in my long-term plan and I will work on it when I have enough knowledge on Shiny models.

**Comment by altairwei** [comment]
@jokergoo It looks like `InteractiveComplexHeatmap` is not available in the shiny module. Do you have any recommendations for references on interactive `ComplexHeatmap`? I noticed your blog post called "Interactive ComplexHeatmap", is there enough content in this blog post to build basic interactivity?

**Comment by jokergoo** [comment]
I think you can check the vignettes of the **InteractiveComplexHeatmap** package or check the preprint https://doi.org/10.1101/2021.03.08.434289.

**Comment by altairwei** [comment]
> I think you can check the vignettes of the **InteractiveComplexHeatmap** package or check the preprint https://doi.org/10.1101/2021.03.08.434289.

Thank you!

**Comment by altairwei** [comment]
@jokergoo After reading *Make Interactive Complex Heatmaps in R*, I tried to use `selectPosition` to implement basic heatmap interactivity. I succeeded, but the coordinates obtained by `selectPosition` do not match the position I actually clicked. Do you have any suggestions? The function `get_pos_from_click` is copied from **InteractiveComplexHeatmap**.

```R
  clicked_mat <- shiny::eventReactive(input$heatmap_click, {
    shiny::req(input$heatmap_click)

    pos <- get_pos_from_click(input$heatmap_click)

    ht <- heatmap_obj()
    ht <- ComplexHeatmap::draw(ht)
    selection <- InteractiveComplexHeatmap::selectPosition(ht, pos)

    row_index <- unique(unlist(selection$row_index))
    col_index <- unique(unlist(selection$column_index))

    mat <- dataset()

    mat[row_index, col_index, drop = FALSE]
  })
```

Besides I always see the following message in the terminal:

```
The heatmaps have been changed. Calculate new heatmap positions.
Search in heatmap 'matrix_4'
  - row slice 1, column slice 1 [matrix_4_heatmap_body_1_1]... no overlap
```

**Comment by altairwei** [comment]
After checking the **InteractiveComplexHeatmap** source code, I realized that maybe I need to cache the ht_pos value when drawing the heatmap. I finally succeeded!

```R
  output$heatmap <- shiny::renderPlot({
    ht <- heatmap_obj()
    ComplexHeatmap::draw(ht)
    ht_pos <- InteractiveComplexHeatmap::htPositionsOnDevice(
      ht, include_annotation = TRUE, calibrate = FALSE)
    ht_pos_cache(ht_pos)
    ht
  })
```

**Comment by jokergoo** [comment]
I think `draw()` should be better to be called inside `plotOutput` because it draws a plot. There is another advantage for the following code is the clustering of the heatmap is also cached.

```r
output$heatmap <- shiny::renderPlot({
    ht = ComplexHeatmap::draw(ht)
    heatmap_obj(ht)
    ht_pos <- InteractiveComplexHeatmap::htPositionsOnDevice(
      ht, include_annotation = TRUE, calibrate = FALSE)
    ht_pos_cache(ht_pos)
    ht
  })

  clicked_mat <- shiny::eventReactive(input$heatmap_click, {
    shiny::req(input$heatmap_click)

    pos <- get_pos_from_click(input$heatmap_click)

    ht <- heatmap_obj()
    selection <- InteractiveComplexHeatmap::selectPosition(
      ht, pos,
      mark = FALSE,
      ht_pos = ht_pos_cache(),
      verbose = FALSE,
      calibrate = FALSE
    )

    row_index <- unique(unlist(selection$row_index))
    col_index <- unique(unlist(selection$column_index))

    mat <- dataset()

    mat[row_index, col_index, drop = FALSE]
  })
```
