### ISSUE TITLE
problems with install 

### ISSUE THREAD

**Issue by mxaxrxkx** [jokergoo/InteractiveComplexHeatmap#66]
Hello, 

When installing the package in Rstudio with:

`install_github("jokergoo/InteractiveComplexHeatmap")`

I am getting an error: 

"Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘ComplexHeatmap’ 2.6.2 is being loaded, but >= 2.7.7 is required
Calls: <Anonymous> ... withCallingHandlers -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted" 

I am using R version 4.0.4 

Any idea how I can solve the problem?

**Comment by jokergoo** [comment]
Then you also need to update ComplexHeatmap from GitHub:

```r
install_github("jokergoo/ComplexHeatmap")
```

**Comment by mxaxrxkx** [comment]
Thanks a lot for a quick reply. Of course it works now. I haven't realized that it is asking to update ComplexHeatmap not InteractiveComplexHeatmap!

**Comment by jokergoo** [comment]
No problem. These two packages are in parallel under development.
