### ISSUE TITLE
Static RMarkdown

### ISSUE THREAD

**Issue by AndrewSkelton** [jokergoo/InteractiveComplexHeatmap#67]
First and foremost, a big thank you for developing such a great and detailed framework. 

I've been trying out InteractiveComplexHeatmap, and love it, but want to share it with people that aren't going to have R installed, and thus a Shiny runtime available. 

Is it possible in the RMarkdown examples to extend this framework to making this run without the need for a shiny runtime?

**Comment by jokergoo** [comment]
No, it is not based on JavaScript, so you must run it under R...

**Comment by AndrewSkelton** [comment]
Thanks for the clarification
