### ISSUE TITLE
Error in originalHeatmapOutput

### ISSUE THREAD

**Issue by riasatazim** [jokergoo/InteractiveComplexHeatmap#68]
package.version("InteractiveComplexHeatmap")
[1] "0.99.10"

package.version("ComplexHeatmap")
[1] "2.7.7"

Error in originalHeatmapOutput("ht", height = 800, containment = TRUE) : 
could not find function "originalHeatmapOutput"

**Comment by jokergoo** [comment]
Please update to the newest version on GitHub. It was called `mainHeatmapOutput`, later I renamed it to `originalHeatmapOutput`.
