### ISSUE TITLE
is it possible to save the InteractiveComplexHeatmap as a webpage?

### ISSUE THREAD

**Issue by klai001** [jokergoo/InteractiveComplexHeatmap#70]
Hi Zuguang

I managed to create a interactive complex heatmap using my data via your InteractiveComplexHeatmap package
and i wish to send the created interactive heatmap as part of a manuscript for the reviewers to access;

I would like to send it as a webpage/zip file for users without R and R's IDE to easily access.

Here is my code in the console  according to your tutorial
i also created a shiny.apps io account; installed rsconnect

```
heatmap
ht=draw(heatmap)
output=htShiny(ht)

ui = fluidPage(
  InteractiveComplexHeatmapOutput()
)

server = function(input, output, session) {
  makeInteractiveComplexHeatmap(input, output, session, ht)
}

shinyapp<-shiny::shinyApp(ui, server)

```

May I know how did you create these links?
e.g. https://jokergooo.shinyapps.io/interactive_tidyheatmap/

**Comment by klai001** [comment]
object `heatmap` is the object i created using ComplexHeatmap package

**Comment by jokergoo** [comment]
There are many tutorial from web, e,g, https://towardsdatascience.com/how-to-publish-a-shiny-app-example-with-shinyapps-io-ec6c6604d8

You save the code into a script e.g. `app.R`, then run the following code:

```r
rsconnect::deployApp('dir-of-app.R", appName = "your-app-name", account = "your-account", server = "shinyapps.io", forceUpdate = TRUE)
```
