### ISSUE TITLE
Error in Cairo: Graphics API version mismatch

### ISSUE THREAD

**Issue by flashlab** [jokergoo/InteractiveComplexHeatmap#73]
Hi, I can't make the demo work after install packages, the error message like this:
```
Listening on http://127.0.0.1:3626
Warning: Error in Cairo: Graphics API version mismatch
  [No stack trace available]
Warning: Error in Cairo: Graphics API version mismatch
  [No stack trace available]
```
Then I tried reinstall R/Rstudio/bioconductor/ComplexHeatmap, but still fail. The version info is
```
R ~ 4.1.0
Rstudio ~ 1.4.1717
ComplexHeatmap ~ 2.9.3
Bioconductor ~ 3.13
```
The demo code is:
```
library(ComplexHeatmap)
library(InteractiveComplexHeatmap)
m = matrix(rnorm(100*100), nrow = 100)
ht = Heatmap(m)
ht = draw(ht) # not necessary, but recommended

htShiny(ht)
```
Wonder if anyone got some idea about the problem. Thanks.

**Comment by flashlab** [comment]
It seems a shiny issue. I got the same error with `runExample("01_hello")`

**Comment by flashlab** [comment]
I solved the issue by reinstall Cairo. Hope it can help anyone who got similar problem.

**Comment by jokergoo** [comment]
This problem is due to the new version of Cairo. I think I will remove the default dependency of Cairo in the future versions of ComplexHeatmap.
