### ISSUE TITLE
Additional controls for subheatmap UI

### ISSUE THREAD

**Issue by j-andrews7** [jokergoo/InteractiveComplexHeatmap#75]
It'd be really nice to be able to change the subheatmap's row/column text size.

**Comment by jokergoo** [comment]
Thanks! I will add it in future versions! (maybe other graphics parameters for texts)

**Comment by jokergoo** [comment]
Current design is you can set `row_names_gp` and `column_names_gp` in the main heatmap, and these two parameters for sub-heatmap are inherited from the main heatmap.
