### ISSUE TITLE
Easy way to round off values when clicking cells in Heatmap?

### ISSUE THREAD

**Issue by raivivek** [jokergoo/InteractiveComplexHeatmap#81]
Hi! Thanks for the great package. I was wondering if there's an easy way, ideally a parameter somewhere to round off the values displayed when clicking a cell. Right now, it shows all the digits probably which isn't too helpful. I imagine one can overload those functions but I am curious to hear what you have to say. Thanks!

**Comment by raivivek** [comment]
Thanks! This is very helpful. You said, three non-zero digits, so it would so show something like "0.80000000041" as well?

**Comment by jokergoo** [comment]
That will be `0.800`. It should be "three digits from the first non-zero digit".

**Comment by raivivek** [comment]
Okay, great! Thanks. I will update to the latest version from GitHub.
