### ISSUE TITLE
same legend label for two heatmaps

### ISSUE THREAD

**Issue by ShinyFabio** [jokergoo/InteractiveComplexHeatmap#82]
Hi,
regarding this example:

https://jokergoo.shinyapps.io/interactive_complexheatmap/

is it possible to use just one legend for both heatmaps? If I add the parameter `"name = "% toxicity""` to both heatmaps, it gives me this error: Heatmap names should not be duplicated. I'm asking this because I have two heatmaps with the same unit scale (0-100%).

**Comment by jokergoo** [comment]
In the second heatmap, you can set `show_heatmap_legend = FALSE`.

```r
m = matrix(rnorm(100), 10)
Heatmap(m) + Heatmap(m, show_heatmap_legend = FALSE)
```

![image](https://user-images.githubusercontent.com/449218/152320246-048ecf68-b995-4a78-bf6c-2b3dd01726f6.png)
