### ISSUE TITLE
Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'fontawesome-5.13.0'; `directoryPath` = ''

### ISSUE THREAD

**Issue by wanlinrong** [jokergoo/InteractiveComplexHeatmap#91]

**Comment by jokergoo** [comment]
Please provide a reproducible example here.

**Comment by wanlinrong** [comment]
I have solved this problem with the latest complexheatmap and interactive complexheatmap from github. Therefore, this may appear in the existing version of bioconductor.
thanks！
