### ISSUE TITLE
Integration between quarto and InteractiveComplexHeatmap

### ISSUE THREAD

**Issue by tiagochst** [jokergoo/InteractiveComplexHeatmap#95]
Hi Zuguang,

Thank you so much for your work on ComplexHeatmap and InteractiveComplexHeatmap.
i was just wondering if you tried to integrate InteractiveComplexHeatmap in a quarto html page https://quarto.org/docs/interactive/shiny/ and if you have an example.

Thank you!

**Comment by jokergoo** [comment]
Emm. I haven't heard of quarto document. It seems it is a variant of the norma rmarkdown. I need to study.

**Comment by tiagochst** [comment]
@jokergoo Don't worry about it. I was looking for a functionality like iheatmapr. Quarto is still a static document as far as I know.

**Comment by tiagochst** [comment]
By the way, thank you for the amazing job with your packages!
