### ISSUE TITLE
`row_names_max_width` in sub-heatmap

### ISSUE THREAD

**Issue by eturkes** [jokergoo/InteractiveComplexHeatmap#99]
Hi Zuguang, this package is excellent and very useful, thank you. I was wondering if there's a way to set this parameter or something similar in the sub-heatmap? My rownames are getting truncated. As a workaround, if you can inform me how to reduce the width for the cells in the sub-heatmap so the rownames fit, I can do that too.

**Comment by jokergoo** [comment]
`row_names_max_width` was not passed to sub-heatmaps. Now it is fixed. Please update it from GitHub and sorry for the late response.

**Comment by eturkes** [comment]
Awesome! Thanks for the update
